package com.webcamconsult.syl.interfaces;

import com.webcamconsult.syl.model.SYLFetchSessionAppointmentResponseModel;

public interface SYLFetchSessionStatusListener {
public void finishFetchSessionAppointmentStatus(SYLFetchSessionAppointmentResponseModel mSylFetchsessionappointmentresponsemodel);
}
